# ////////////////////////
# FILE PATH
# ////////////////////////
# caledon-address: '/Users/mac/Downloads/caledon/caledon-address.geojson'
# caledon-buildings: '/Users/mac/Downloads/caledon/caledon-building.geojson'
# caledon-buildings-address: '/Users/mac/Downloads/caledon/caledon-building-address.geojson'

# ////////////////////////
# URL
# ////////////////////////
caledon-address: 'https://gist.github.com/DenisCarriere/312775d66fc136f4d91b26e5c7b8fd65/raw/bce13d55f3e5053ab3b945efc0b0de0e690b6bf4/caledon-address.geojson'
caledon-buildings: 'https://gist.github.com/DenisCarriere/218598adeccf51ed09313fd2c9f28350/raw/04284a625d60503c0942f10de9d06e8f12eb52a9/caledon-buildings.geojson'
caledon-buildings-address: 'https://gist.github.com/DenisCarriere/263312e80d9b3d17376ee2b64a0a7ff7/raw/430777c8c373ee39a54cecc7731877d414dd4045/caledon-buildings-address.geojson'
gatineau-fire-hydrants: 'https://gist.githubusercontent.com/DenisCarriere/0b245ca9922ecbc499a9408d374dd4f6/raw/c2790662b296f7a426a492cdc5ed6f142f5e72a2/gatineau-fire-hydrants.geojson'
ottawa-ball-diamonds: 'https://gist.githubusercontent.com/DenisCarriere/4d0ebc8126eb0c4bffe7b0bd5ee029c9/raw/2af406db35332898aae1aa72c0aae68188504b59/ball-diamonds.geojson'

# ////////////////////////
# TODO
# ////////////////////////
# ottawa-bus-routes: 'https://transit.land/api/v1/routes.geojson?operated_by=o-f24-octranspo'
# ottawa-splash-pads: 'http://data.ottawa.ca/dataset/493ec7fd-7aff-4003-995c-5f0557d375c6/resource/9ada2541-539d-455a-b450-6c76dfc9b3e3/download/splash-pads.json'
# ottawa-outdoor-rinks: 'http://data.ottawa.ca/dataset/3a19f905-e0fb-4afb-81fe-aff54a08b268/resource/dff7eb5c-3392-47d3-a6a4-4440ccdc0b77/download/outdoor-rinks.json'
# ottawa-volleyball-courts: 'http://data.ottawa.ca/dataset/401dfd09-ea0a-4864-a015-87af39ffc8da/resource/0fbea1f1-a91b-4f76-b9c8-e82aa1cf3375/download/volleyball-courts.json'
# ottawa-public-washrooms: 'http://data.ottawa.ca/dataset/e883ac3c-5e99-468e-b9d5-c2bf0015af68/resource/45f4c2ad-327e-4eef-8d7c-1772fc3d8e56/download/publicwashrooms.json'
# ottawa-wards: 'http://data.ottawa.ca/dataset/13deeed4-1cd5-4a68-a10d-9839d3677446/resource/39333199-c9b5-4dc8-bb59-0a9422c23f63/download/wards-2010-2.json'
