# Bing
# ====
# - imagery
bing:
  name: 'Bing Imagery'
  scheme: 'http://ecn.t{switch:0,1,2,3}.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?g=5250'
  description: 'Tiles from Bing'
  attribution: 'Map data © Bing'
  format: 'jpg'

imagery:
  name: 'Bing Imagery'
  scheme: 'http://ecn.t{switch:0,1,2,3}.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?g=5250'
  description: 'Tiles from Bing'
  attribution: 'Map data © Bing'
  format: 'jpg'

# Strava
# =======
# - both
# - cycle
# - foot
strava:
  name: 'Strava Cycling & Running'
  scheme: 'https://globalheat.strava.com/tiles/both/color/{zoom}/{x}/{y}.png'
  description: 'Tiles from Strava'
  attribution: 'Map data © Strava'
  format: 'png'

# Open Street map
# ===============
# - cycle
# - hot
# - standard
# - transport
osm:
  name: 'OSM Standard'
  scheme: 'https://{switch:a,b,c}.tile.openstreetmap.org/{zoom}/{x}/{y}.png'
  description: 'Tiles from OSM'
  attribution: 'Map data © OSM'
  format: 'png'

osm-cycle:
  name: 'OSM Cycle Map'
  scheme: 'https://{switch:a,b,c}.tile.thunderforest.com/cycle/{zoom}/{x}/{y}.png'
  description: 'Tiles from OSM'
  attribution: 'Map data © OSM'
  format: 'png'

osm-hot:
  name: 'OSM Humanitarian'
  scheme: 'https://tile-{switch:a,b,c}.openstreetmap.fr/hot/{zoom}/{x}/{y}.png'
  description: 'Tiles from OSM'
  attribution: 'Map data © OSM'
  format: 'png'

osm-standard:
  name: 'OSM Standard'
  scheme: 'https://{switch:a,b,c}.tile.openstreetmap.org/{zoom}/{x}/{y}.png'
  description: 'Tiles from OSM'
  attribution: 'Map data © OSM'
  format: 'png'

osm-transport:
  name: 'OSM Transport Map'
  scheme: 'https://{switch:a,b,c}.tile.thunderforest.com/transport/{zoom}/{x}/{y}.png'
  description: 'Tiles from OSM'
  attribution: 'Map data © OSM'
  format: 'png'

osm-wikimedia:
  name: 'OSM Wikimedia'
  scheme: 'https://maps.wikimedia.org/osm-intl/{zoom}/{x}/{y}.png'
  description: 'Tiles from OSM'
  attribution: 'Map data © OSM'
  format: 'png'

# ESRI
# ====
# - natgeo
# - ocean
# - usa-topo
# - imagery
# - street
# - topo
esri-natgeo:
  name: 'National Geographic World Map'
  scheme: 'https://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{zoom}/{y}/{x}'
  description: 'This map is designed to be used as a general reference map for informational and educational purposes as well as a basemap by GIS professionals and other users for creating web maps and web mapping applications.'
  attribution: 'National Geographic, Esri, DeLorme, HERE, UNEP-WCMC, USGS, NASA, ESA, METI, NRCAN, GEBCO, NOAA, INCREMENT P'
  format: 'jpg'

esri-ocean:
  name: 'Ocean Basemap'
  scheme: 'https://services.arcgisonline.com/ArcGIS/rest/services/Ocean_Basemap/MapServer/tile/{zoom}/{y}/{x}'
  description: 'The ocean basemap includes bathymetry, surface and subsurface feature names, and derived depths. This service is designed to be used as a basemap by marine GIS professionals and as a reference map by anyone interested in ocean data.'
  attribution: 'Esri, GEBCO, NOAA, National Geographic, DeLorme, HERE, Geonames.org, and other contributors'
  format: 'jpg'

esri-usa-topo:
  name: 'USA Topo Maps'
  scheme: 'https://services.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer/tile/{zoom}/{y}/{x}'
  description: 'This map service presents detailed USGS topographic maps for the United States at multiple scales.'
  attribution: '© 2011 National Geographic Society, i-cubed'
  format: 'jpg'

esri-imagery:
  name: 'ESRI World Topographic Map'
  scheme: 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{zoom}/{y}/{x}'
  description: 'This map service presents satellite imagery for the world and high-resolution imagery for the United States and other areas around the world.'
  attribution: 'Esri, DigitalGlobe, Earthstar Geographics, CNES/Airbus DS, GeoEye, USDA FSA, USGS, Getmapping, Aerogrid, IGN, IGP, and the GIS User Community'
  format: 'jpg'

esri-street:
  name: 'World Street Map'
  scheme: 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{zoom}/{y}/{x}'
  description: 'This map service presents highway-level data for the world and street-level data for North America, Europe, Africa, parts of the Middle East, Asia, and more.'
  attribution: 'Esri, HERE, DeLorme, USGS, Intermap, INCREMENT P, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), MapmyIndia, © OpenStreetMap contributors, and the GIS User Community'
  format: 'jpg'

esri-topo:
  name: 'ESRI World Topographic Map'
  scheme: 'https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{zoom}/{y}/{x}'
  description: 'This world topographic map includes boundaries, cities, water features, physiographic features, parks, landmarks, transportation, and buildings.'
  attribution: 'Esri, HERE, DeLorme, Intermap, INCREMENT P, GEBCO, USGS, FAO, NPS, NRCAN, GeoBase, IGN, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), swisstopo, MapmyIndia, © OpenStreetMap contributors, GIS User Community'
  format: 'jpg'